token: "Mzc3NjE3NjMwMzYzNjQ4MDAw.DOPjZg.Z7-4BQFUwnhE4rJLwVl8-ycNzwk"

guild_id: 123456789

base_voice: "Voice"

owner_id: 

discord_bots_key: 123456

postgres_credentials:
    host: "localhost"
    user: "yinbotuser"
    database: "yinbot"
    password: "testpass"